# Uncomment the next line to define a global platform for your project

platform :ios, '9.0'

target 'Nec' do
 
 pod 'AFNetworking','~> 2.5.0'
    pod 'Masonry', '~> 1.0.2'
    pod 'SDWebImage', '~>3.8'
    pod 'TZImagePickerController'
    pod 'MarqueeLabel', '~> 3.0.1'
    pod 'IQKeyboardManager', '~> 5.0.6’
    pod 'Bugly'
    pod ‘BaiduMobStatCodeless'
    pod 'SocketRocket'

end
